CREATE TABLE tb_user
(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 email VARCHAR(200) NOT NULL,
 password VARCHAR(129) NOT NULL,
 name VARCHAR(120) NULL,
 PRIMARY KEY (id)
);
COMMENT ON COLUMN tb_user.id IS 'unique identifier of the user';
COMMENT ON COLUMN tb_user.email IS 'email for user';
COMMENT ON COLUMN tb_user.password IS 'password';
COMMENT ON TABLE tb_user IS 'All users';
---
CREATE TABLE tb_user_external_project
(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 user_id BIGINT NOT NULL,
 name VARCHAR(120) NOT NULL,
 PRIMARY KEY (id, user_id),
 CONSTRAINT fk_user
 FOREIGN KEY (user_id)
 REFERENCES tb_user(id)
 ON DELETE CASCADE
);
COMMENT ON COLUMN tb_user_external_project.id IS 'identifier of external project';
COMMENT ON COLUMN tb_user_external_project.user_id IS 'unique identifier of the user';
COMMENT ON COLUMN tb_user_external_project.name IS 'Name of external project';
COMMENT ON TABLE tb_user_external_project IS 'External Project identifier for users';
---
INSERT INTO tb_user ("id", "email", "password", "name") VALUES (0, 'test@test.com', '$2a$12$rl7QKXpphPSy32bREF7G7.B.XyoI7sdyQkRx0BqXsXoOl133H5u7m', 'Test User');